#!/usr/bin/env python3
"""Generate the static GitHub Pages site using only the Python standard library."""
import json
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
PAGES = json.loads((ROOT / "src/pages.json").read_text())
ORDER = list(dict.fromkeys(page["tab"] for page in PAGES if page["visible"]))


def build():
    rendered = {}
    for page in PAGES:
        active = page["tab"]
        tabs = ORDER + ([active] if active not in ORDER else [])
        content = (ROOT / "src/pages" / page["file"]).read_text()
        panels = []
        for number, tab in enumerate(tabs, 1):
            label = next(p["label"] for p in PAGES if p["tab"] == tab)
            key = f"tab-{tab}"
            if tab == active:
                panels.append(f'<div class="page-panel" data-tab-key="{key}" aria-label="{escape(label)}">\n{content}</div>')
                active_number = number
            else:
                filename = "index.html" if tab == "index" else f"{tab}.html"
                panels.append(f'<a class="page-tab" data-tab-key="{key}" href="{filename}"><span class="tab-rail"><span class="tab-number">{number:02}</span><span class="tab-label">{escape(label)}</span></span></a>')
        body = "\n".join(panels)
        html = f'''<!doctype html>
<!-- Generated by scripts/build.py; edit src/pages/{page["file"]} instead. -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#000000">
    <meta name="color-scheme" content="dark light">
    <title>nodavex</title>
    <script src="assets/js/theme.js"></script>
    <link rel="icon" type="image/svg+xml" href="favicon.svg">
    <link rel="stylesheet" href="assets/css/site.css">
    <script src="assets/js/page-data.js" defer></script>
    <script src="assets/js/navigation.js" defer></script>
  </head>
  <body>
    <button class="theme-toggle" type="button" aria-label="Switch to light mode">Light mode</button>
    <div class="tab-stage">
      <span class="active-tab-number" style="left: {(active_number - 1) * 36}px" aria-label="Current page {active_number:02}"><span>{active_number:02}</span><span class="active-tab-label">{escape(page["label"])}</span></span>
      <div class="site-frame" aria-label="nodavex pages">
{body}
      </div>
    </div>
  </body>
</html>
'''
        (ROOT / page["file"]).write_text(html)
        rendered[page["file"]] = html
    (ROOT / "assets/js/page-data.js").write_text(
        "// Generated local-file preview data.\nwindow.NODAVEX_PAGES = "
        + json.dumps(rendered) + ";\n"
    )
    print(f"Built {len(rendered)} pages.")


if __name__ == "__main__":
    build()
